CREATE TABLE cash_book_maintenance (
    transaction_id    NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cashbook_code     VARCHAR2(50) NOT NULL,
    transaction_date  DATE DEFAULT SYSDATE NOT NULL,
    description       VARCHAR2(255) NOT NULL,
    voucher_type      VARCHAR2(10) CHECK (voucher_type IN ('RECEIPT', 'PAYMENT')),
    receipt_amount    NUMBER(15,2) DEFAULT 0.00,
    payment_amount    NUMBER(15,2) DEFAULT 0.00,
    running_balance   NUMBER(15,2) DEFAULT 0.00,
    currency_code     VARCHAR2(3) DEFAULT 'USD' NOT NULL,
    created_by        VARCHAR2(100) DEFAULT USER,
    creation_date     DATE DEFAULT SYSDATE
);

-- Create an index on frequently queried columns for performance
CREATE INDEX idx_cb_code_date ON cash_book_maintenance (cashbook_code, transaction_date);




-- Drop tables if they already exist (clean re-creation)
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE petty_cash_voucher_dtl CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE petty_cash_voucher_hdr CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

-- 1. Create Petty Cash Voucher Header Table
CREATE TABLE petty_cash_voucher (
    voucher_id        NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    voucher_no        VARCHAR2(50) NOT NULL UNIQUE,
    voucher_date      DATE DEFAULT SYSDATE NOT NULL,
    fund_code         VARCHAR2(30) NOT NULL, -- Identifies specific petty cash float/fund
	expense_category  VARCHAR2(100) NOT NULL, -- e.g., Office Supplies, Transport
    custodian_name    VARCHAR2(100) NOT NULL, -- Person managing/disbursing cash
    receiver_name     VARCHAR2(100) NOT NULL, -- Person receiving the cash
    description       VARCHAR2(500),          -- Purpose / Explanation of expense
    receipt_ref_no    VARCHAR2(50),           -- Physical receipt/invoice number
    amount            NUMBER(15,2) NOT NULL,
    status            VARCHAR2(20) DEFAULT 'DRAFT' NOT NULL, -- DRAFT, APPROVED, POSTED, CANCELLED
    approved_by       VARCHAR2(100),
    remarks           VARCHAR2(4000),
    created_by        VARCHAR2(50) DEFAULT USER,
    creation_date     DATE DEFAULT SYSDATE,
    last_updated_by   VARCHAR2(50) DEFAULT USER,
    last_update_date  DATE DEFAULT SYSDATE
);

-- 2. Create Petty Cash Voucher Detail (Line Items) Table
CREATE TABLE petty_cash_voucher_dtl (
    line_id           NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    voucher_id        NUMBER NOT NULL,
    line_no           NUMBER NOT NULL,
    expense_category  VARCHAR2(100) NOT NULL, -- e.g., Office Supplies, Transport
    gl_account_code   VARCHAR2(50) NOT NULL,  -- Corresponding General Ledger Account
    description       VARCHAR2(500),          -- Purpose / Explanation of expense
    amount            NUMBER(15,2) NOT NULL,
    receipt_ref_no    VARCHAR2(50),           -- Physical receipt/invoice number
    CONSTRAINT fk_voucher_hdr FOREIGN KEY (voucher_id) 
        REFERENCES petty_cash_voucher_hdr(voucher_id) ON DELETE CASCADE
);

-- Add indexes for performance optimization during reporting/searches
CREATE INDEX idx_pv_hdr_date ON petty_cash_voucher_hdr(voucher_date);
CREATE INDEX idx_pv_hdr_fund ON petty_cash_voucher_hdr(fund_code);
CREATE INDEX idx_pv_dtl_acc ON petty_cash_voucher_dtl(gl_account_code);
